# Generated by Django 4.2.16 on 2024-11-12 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "WearWellWardrobe",
            "0002_alter_category_options_alter_counts_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="WearWellWardrobe.category",
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="content1",
            field=models.CharField(blank=True, default="", max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content2",
            field=models.CharField(blank=True, default="", max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content3",
            field=models.CharField(blank=True, default="", max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="content4",
            field=models.CharField(blank=True, default="", max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="img1",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="contentPhotos/"
            ),
        ),
        migrations.AlterField(
            model_name="page",
            name="slug",
            field=models.SlugField(blank=True, default="", null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(
                blank=True, default="Untitled", max_length=128, null=True
            ),
        ),
    ]
