# Generated by Django 4.2.16 on 2024-11-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("WearWellWardrobe", "0003_alter_page_category_alter_page_content1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="displayStyle",
            field=models.IntegerField(default=1),
        ),
    ]
